### ISSUE TITLE
How does it perform against nginx?

### ISSUE THREAD

**Issue by tonsV2** [abhin4v/hastatic#1]

**Comment by abhin4v** [comment]
Is this question because of curiosity or do you really want to replace nginx with this minimal server in high traffic scenarios? This article gives a comparison of Warp, the core of hastatic, against nginx: https://www.aosabook.org/en/posa/warp.html. Here's a graph from the same:

![Performance of Warp and nginx](https://www.aosabook.org/en/posa/warp-images/benchmark.png)

**Comment by tonsV2** [comment]
I've been using nginx for serving of static and php content for many many years without thinking about it. When I came across your repo it struck me that since I also put everything in a container now adays it might be time to see if there is something better suited than nginx... Hence the question. Thanks for the link, I'll google a bit and probably continue to use nginx for the time being.
